### PR TITLE
Fix: Updating aws-ts-apigateway-lambda-serverless for TS2339, fixes 2159

### LINKED ISSUE #2159: TS2339: Property apigateway does not exist on type
It seems that "apigateway" doesn't exist in this package anymore?

screenshot:
Image

reference:
https://github.com/pulumi/examples/blob/76076a0c6d2e142c9abd72211749ae2c2ce9f5ac/aws-ts-apigateway-lambda-serverless/index.ts#L11

### PR DESCRIPTION
**Pull request by rshade**
This pull request includes several changes to improve the AWS API Gateway and Lambda serverless setup. The most important changes involve importing additional modules, modifying the handler function to include context, and creating separate Lambda functions for each HTTP method.

### Improvements to Lambda handler:

* [`aws-ts-apigateway-lambda-serverless/handler.ts`](diffhunk://#diff-0a564020005e94424a9318c3ad252cb4119c4304b15ebe92e953385768f0b355L4-R17): Modified the handler function to include the `Context` parameter and updated the function signature to use `APIGatewayProxyEvent` and `APIGatewayProxyResult` types.

### Enhancements to API Gateway setup:

* [`aws-ts-apigateway-lambda-serverless/index.ts`](diffhunk://#diff-cbf043ee80f083bc116640a425c2f7c19700de323da4fef1d55d0a8faf851bc7L3-R60): Replaced the use of `awsx.apigateway.API` with `apigateway.RestAPI`, and created separate Lambda functions for GET, POST, and DELETE methods using `aws.lambda.CallbackFunction`.

### Dependency updates:

* [`aws-ts-apigateway-lambda-serverless/package.json`](diffhunk://#diff-4c66d2c846846f26db19087ce1526a6ed4a1ba78ed5947f6e7e47187496e39a4R9): Added `@pulumi/aws-apigateway` as a new dependency.
This fixes #2159

### CODE REVIEW

File: aws-ts-apigateway-lambda-serverless/index.ts [hunk 1]
```diff
@@ -1,38 +1,63 @@
...
+      statusCode: 200,
+      body: JSON.stringify({ message: "POST successful" }),
+    };
+  },
+  runtime: aws.lambda.Runtime.NodeJS18X,
+});
+
+const deleteHandlerFunction = new aws.lambda.CallbackFunction("delete-handler", {
+  callback: async (event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> => {
+    console.log("Inline delete event handler");
```
Comment (mjeffryes) [inline aws-ts-apigateway-lambda-serverless/index.ts:33]: this is kind of a lie now. I think the point had previously been to show how you could write a handler inline vs pointing to a function. Now these are all `CallbackFunction` instances.

File: CLAUDE.md [hunk 2]
```diff
@@ -0,0 +1,25 @@
+# CLAUDE.md
```
Comment (mjeffryes) [inline CLAUDE.md:1]: I have mixed feelings about checking this in to encourage more AI contributions.

**Review by mjeffryes — APPROVED** [review]
Thanks for the fix
