### PR TITLE
Fix Go AWS S3 example

### LINKED ISSUE #113: `aws-go-s3-folder` example doesn't show stack outputs
When running `pulumi up` the stack outputs are not shown:

```bash
$ pulumi up
Previewing update of stack 'website-dev'
Previewing changes:

     Type                     Name                 Plan       Info
 +   pulumi:pulumi:Stack      website-website-dev  create     
 +   ├─ pulumi:providers:aws  default              create     
 +   ├─ aws:s3:Bucket         s3-website-bucket    create     
 +   ├─ aws:s3:BucketPolicy   bucketPolicy         create     
 +   ├─ aws:s3:BucketObject   www/index.html       create     
 +   └─ aws:s3:BucketObject   www/favicon.png      create     
 
info: 5 changes previewed:
    + 5 resources to create

Do you want to perform this update? yes
Updating stack 'website-dev'
Performing changes:

     Type                    Name                 Status      Info
 +   pulumi:pulumi:Stack     website-website-dev  created     
 +   ├─ aws:s3:Bucket        s3-website-bucket    created     
 +   ├─ aws:s3:BucketPolicy  bucketPolicy         created     
 +   ├─ aws:s3:BucketObject  www/index.html       created     
 +   └─ aws:s3:BucketObject  www/favicon.png      created     
 
info: 5 changes performed:
    + 5 resources created
Update duration: 7.633434765s

Permalink: https://app.pulumi.com/***
```

Also, when running `pulumi stack` it says "No output values currently in this stack":

```bash
$ pulumi stack

[...]

Current stack resources (6):
    TYPE                                             NAME
    pulumi:pulumi:Stack                              website-website-dev
    pulumi:providers:aws                             default
    aws:s3/bucket:Bucket                             s3-website-bucket
    aws:s3/bucketPolicy:BucketPolicy                 bucketPolicy
    aws:s3/bucketObject:BucketObject                 www/index.html
    aws:s3/bucketObject:BucketObject                 www/favicon.png

Current stack outputs (0):
    No output values currently in this stack
```

I'm not sure if it's a bug in our `go` support or bug in the example.

### PR DESCRIPTION
**Pull request by justone**
* Files are now uploaded without www path prefix
* Mime types now properly detected
* Output registration requires method calls, not methods

Fixes #113

### CODE REVIEW

**Comment by justone** [comment]
cc/ @swgillespie

File: aws-go-s3-folder/main.go [hunk 1]
```diff
@@ -77,3 +78,8 @@ func publicReadPolicyForBucket(bucketName pulumi.ID) (interface{}, error) {
 	})
 	return string(policy), nil
 }
+
+// ext returns the extension of the fileName.
+func ext(fileName string) string {
```
Comment (lukehoban) [inline aws-go-s3-folder/main.go]: Can this just be [`path.Ext`](https://golang.org/pkg/path/#Ext)?

Comment (justone) [reply aws-go-s3-folder/main.go]: Ah, very nice.  Will update.

Comment (justone) [reply aws-go-s3-folder/main.go]: Done.
